services:
  trabajo-individual:
    image: trabajo-individual
    build: .
    ports:
      - "8081:8081"
    environment:
      - SERVICIO_URL=http://app:8080
    networks:
      - trabajo_grupal_tt1_2026_solicitudes_network

networks:
  trabajo_grupal_tt1_2026_solicitudes_network:
    external: true